[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "mcbifrost"
dependencies = [
    'zenlog==1.1,',
    "importlib_metadata; python_version<'3.8'",
]
dynamic = ["version"]

[project.scripts]
mcbifrost_run = "mcbifrost.run:run"

[tool.setuptools_scm]
